### ISSUE TITLE
Build fails on snapshot 04-12

### ISSUE THREAD

**Issue by adrianbrink** [PlanTeam/MongoKitten#19]
Hi,

the library doesn't install on the latest snapshot (04-12)

```
→ swift build
Cloning https://github.com/PlanTeam/MongoKitten.git
Resolved version: 0.5.12
Cloning https://github.com/cryptokitten/md5.git
Resolved version: 0.1.1
Cloning https://github.com/CryptoKitten/CryptoEssentials.git
Resolved version: 0.2.1
Cloning https://github.com/SwiftX/C7.git
Resolved version: 0.2.0
Cloning https://github.com/cryptokitten/scram.git
Resolved version: 0.3.2
Cloning https://github.com/CryptoKitten/PBKDF2.git
Resolved version: 0.3.1
Cloning https://github.com/CryptoKitten/HMAC.git
Resolved version: 0.3.1
Cloning https://github.com/CryptoKitten/SHA1.git
Resolved version: 0.3.2
Cloning https://github.com/planteam/bson.git
Resolved version: 1.2.7
Cloning https://github.com/qutheory/hummingbird.git
Resolved version: 1.1.2
Cloning https://github.com/ketzusaka/Strand
Resolved version: 1.1.0
Compiling Swift Module 'C7' (14 sources)
Compiling Swift Module 'Strand' (1 sources)
Compiling Swift Module 'BSON' (22 sources)
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/Strand-1.1.0/Sources/Strand.swift:29:38: error: nil cannot initialize specified type 'pthread_t' (aka 'UnsafeMutablePointer<_opaque_pthread_t>')
    private var pthread: pthread_t = nil
                                     ^
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/Strand-1.1.0/Sources/Strand.swift:40:30: error: cannot pass immutable value as inout argument: implicit conversion from 'pthread_t' to 'pthread_t?' requires a temporary
        guard pthread_create(&pthread, nil, runner, pointer) == 0 else { throw StrandError.threadCreationFailed }
                             ^~~~~~~~
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/Strand-1.1.0/Sources/Strand.swift:73:12: error: nil is incompatible with return type 'UnsafeMutablePointer<Void>' (aka 'UnsafeMutablePointer<()>')
    return nil
           ^
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/C7-0.2.0/Sources/AsyncStream.swift:4:18: warning: extraneous duplicate parameter name; 'length' already has an argument label
    func receive(length length: Int, result: (Void throws -> Data) -> Void)
                 ^~~~~~~

/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/C7-0.2.0/Sources/AsyncStream.swift:5:15: warning: extraneous duplicate parameter name; 'data' already has an argument label
    func send(data data: Data, result: (Void throws -> Void) -> Void)
              ^~~~~

/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/C7-0.2.0/Sources/Data.swift:34:26: error: method 'replaceSubrange(subRange:with:)' has different argument names from those required by protocol 'RangeReplaceableCollection' ('replaceSubrange(_:with:)')
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Byte>(subRange: Range<Int>, with newElements: C) {
                         ^
                                                                                          _
Swift.RangeReplaceableCollection:16:26: note: requirement 'replaceSubrange(_:with:)' declared here
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Iterator.Element>(_ subRange: Range<Self.Index>, with newElements: C)
                         ^
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/C7-0.2.0/Sources/Data.swift:34:26: error: method 'replaceSubrange(subRange:with:)' has different argument names from those required by protocol 'RangeReplaceableCollection' ('replaceSubrange(_:with:)')
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Byte>(subRange: Range<Int>, with newElements: C) {
                         ^
                                                                                          _
Swift.RangeReplaceableCollection:16:26: note: requirement 'replaceSubrange(_:with:)' declared here
    public mutating func replaceSubrange<C : Collection where C.Iterator.Element == Iterator.Element>(_ subRange: Range<Self.Index>, with newElements: C)
                         ^
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/BSON-1.2.7/Sources/Document+SequenceType.swift:91:36: warning: extraneous duplicate parameter name; 'keepCapacity' already has an argument label
    public mutating func removeAll(keepCapacity keepCapacity: Bool = false) {
                                   ^~~~~~~~~~~~~

/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/BSON-1.2.7/Sources/Document+SequenceType.swift:34:33: error: missing argument label 'value:' in call
                self.updateValue(newValue, forKey: key)
                                ^
                                 value:
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/BSON-1.2.7/Sources/Document+SequenceType.swift:36:40: error: missing argument label 'key:' in call
                self.removeValueForKey(key)
                                       ^
                                       key:
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/BSON-1.2.7/Sources/Document+SequenceType.swift:64:47: error: missing argument label 'key:' in call
        guard let indexKey = self.indexForKey(key) else {
                                              ^
                                              key:
/Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/Packages/BSON-1.2.7/Sources/Document+SequenceType.swift:83:44: error: missing argument label 'key:' in call
        guard let index = self.indexForKey(key) else {
                                           ^
                                           key:
<unknown>:0: error: build had 3 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a.xctoolchain/usr/bin/swift-build-tool -f /Users/aevitas/Desktop/Coding/Swift/Server/league-downloader/.build/debug.yaml default
```

Any help will be appreciated.

**Comment by Joannis** [comment]
Hello @adrianbrink . Currently we're working on MongoKitten 1.0.0 which already supports 04-12. If you want to use MongoKitten on Swift 04-12 use the tag "0.0.0" `majorVersion: 0, minor: 0`.
It is a bit unstable. Not all the new features have been tested and documented by us. Neither in unit tests nor actual usage. And we're still possibly changing the API a little.

If you really want to use MongoKitten with 04-12 that's your only option right now. If you want to help. Join either the Zewo or Qutheory slack channels and you can find me/obbut there. The main problem our library currently faces is the lack of input from our users. So any input you can give us will help us settle on a good API faster which leads to a faster 1.0 release.

**Comment by Joannis** [comment]
Update: https://supportkitten.slack.com/

**Comment by adrianbrink** [comment]
@Joannis I would be happy to help. 👍 How do I join the two slack channels? I think you have to invite me. For that purpose you can use: adrian@brink-holdings.com

Thank you for the info, I'll try out "0.0.0".

**Comment by Joannis** [comment]
@adrianbrink 0.7.0 has been released today. Things could change for 1.0.0 but I doubt most of it will change

**Comment by adrianbrink** [comment]
Should I still be using "0.0.0" or now "0.7.0". I am quite new to how SPM handles versions.

**Comment by Joannis** [comment]
You can use 0.7.0 now
